"use strict";
exports.FEED_ADD = 'Feed: add new';
exports.FEED_ADD_FAIL = 'Feed: add new fail';
exports.FEED_ADD_SUCCESS = 'Feed: add new success';
exports.FEED_ADD_COMMENT = 'Feed: add new comment';
exports.FEED_ADD_COMMENT_FAIL = 'Feed: add new comment fail';
exports.FEED_ADD_COMMENT_SUCCESS = 'Feed: add new comment success';
exports.FEED_REMOVE = 'Feed: remove';
exports.FEED_REMOVE_FAIL = 'Feed: remove fail';
exports.FEED_REMOVE_SUCCESS = 'Feed: remove success';
