"use strict";
exports.WEATHER_GET = 'Weather: get weather for selected city';
exports.WEATHER_GET_SUCCESS = 'Weather: weather successfully get';
exports.WEATHER_GET_FAIL = 'Weather: error while fetching data';
exports.AIR_QUALITY_GET = 'Weather: get air quality';
exports.AIR_QUALITY_GET_SUCCESS = 'Weather: air quality successfully get';
exports.AIR_QUALITY_GET_FAIL = 'Weather: error while fetching air quality';
exports.SELECT_CITY = 'Weather: Select city';
exports.WEATHER_DATA_GET = 'Weather: get weather data';
exports.WEATHER_DATA_GET_SUCCESS = 'Weather: weather data successfully get';
exports.WEATHER_DATA_GET_FAIL = 'Weather: error while fetching wearher data';
